refactor(scripts): reformat

diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,13 +6,13 @@ RELEASES_URL="https://github.com/metafates/mangal/releases"
 FILE_BASENAME="mangal"
 
 test -z "$VERSION" && VERSION="$(curl -sfL -o /dev/null -w "%{url_effective}" "$RELEASES_URL/latest" |
-		rev |
-		cut -f1 -d'/'|
-		rev)"
+  rev |
+  cut -f1 -d'/' |
+  rev)"
 
 test -z "$VERSION" && {
-	echo "Unable to get mangal version." >&2
-	exit 1
+  echo "Unable to get mangal version." >&2
+  exit 1
 }
 
 test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
@@ -24,18 +24,17 @@ export TAR_NAME
 export TAR_FILE
 
 (
-	cd "$TMPDIR"
+  cd "$TMPDIR"
 
-	echo "Downloading Mangal $VERSION..."
-	curl -sfLo "$TAR_FILE" \
-		"$RELEASES_URL/download/$VERSION/${TAR_NAME}"
+  echo "Downloading Mangal $VERSION..."
+  curl -sfLo "$TAR_FILE" \
+    "$RELEASES_URL/download/$VERSION/${TAR_NAME}"
 
   echo "Downloading checksums..."
-	curl -sfLo "checksums.txt" "$RELEASES_URL/download/$VERSION/checksums.txt"
+  curl -sfLo "checksums.txt" "$RELEASES_URL/download/$VERSION/checksums.txt"
 
-	echo "Verifying checksums..."
-  if command -v sha256sum &> /dev/null
-  then
+  echo "Verifying checksums..."
+  if command -v sha256sum &>/dev/null; then
     sha256sum --ignore-missing --quiet --check checksums.txt
   else
     shasum -a 256 --ignore-missing --quiet --check checksums.txt
@@ -44,4 +43,3 @@ export TAR_FILE
 
 tar -xf "$TAR_FILE" -C "$TMPDIR"
 "${TMPDIR}/${FILE_BASENAME}" "$@"
-
