refactor(scripts): improve install script

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -8,15 +8,15 @@ has() {
 }
 
 info() {
-    printf "\033[1;35minfo:\033[0m %s\n" "$1"
+    printf "\033[1;35mInfo:\033[0m %s\n" "$1"
 }
 
 warn() {
-    echo "warn: $1"
+    printf "\033[1;33mWarning:\033[0m %s\n" "$1"
 }
 
 err() {
-    printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
+    printf "\033[1;31mError:\033[0m %s\n" "$1" >&2
 }
 
 die() {
@@ -32,16 +32,21 @@ download() {
 verify_checksums() {
     info "Verifying checksums..."
     if has sha256sum; then
-        sha256sum --ignore-missing --quiet --check checksums.txt
+        OK=$(sha256sum --ignore-missing --quiet --check checksums.txt)
     else
-        shasum -a 256 --ignore-missing --quiet --check checksums.txt
+        OK=$(shasum -a 256 --ignore-missing --quiet --check checksums.txt)
+    fi
+
+    if ! $OK;
+    then
+        die "Checksums mismatch. Abort"
     fi
 }
 
 install_deb() {
     if ! has dpkg;
     then
-        warn "dpkg is not in path. Using alternative method..."
+        warn "dpkg is not available. Using alternative method..."
         install_binary
         return
     fi
@@ -54,8 +59,7 @@ install_deb() {
     RPM_NAME="${FILE_BASENAME}_${VERSION}_${ARCH}.deb"
     RPM_FILE="$TMPDIR/$RPM_NAME"
 
-    export RPM_FILE
-    export RPM_NAME
+    export RPM_FILE RPM_NAME
 
     (
         cd "$TMPDIR"
@@ -84,8 +88,7 @@ install_binary() {
     TAR_NAME="${FILE_BASENAME}_${VERSION}_${OS}_${ARCH}.tar.gz"
     TAR_FILE="$TMPDIR/$TAR_NAME"
 
-    export TAR_NAME
-    export TAR_FILE
+    export TAR_NAME TAR_FILE
 
     (
         cd "$TMPDIR"
@@ -101,9 +104,8 @@ install_binary() {
 
     tar -xf "$TAR_FILE" -C "$TMPDIR"
 
-    info "Installing..."
     OUT="/usr/local/bin/"
-    info "Linux detected. Moving to ${OUT}"
+    info "Moving to ${OUT}"
     sudo sh -c "install '$TMPDIR/$FILE_BASENAME' '${OUT}'"
 }
 
@@ -114,14 +116,14 @@ install_macos() {
         return
     fi
 
-    info "Installing with homebrew"
+    info "Installing with homebrew..."
     brew tap metafates/mangal
     brew install mangal
 }
 
 install_rpm() {
     if ! has rpm; then
-        warn "rpm is not in path. Using alternative method..."
+        warn "rpm is not available. Using alternative method..."
         install_binary
         return
     fi
@@ -129,8 +131,7 @@ install_rpm() {
     RPM_NAME="${FILE_BASENAME}-${VERSION}.${ARCH}.rpm"
     RPM_FILE="$TMPDIR/$RPM_NAME"
 
-    export RPM_FILE
-    export RPM_NAME
+    export RPM_FILE RPM_NAME
 
     (
         cd "$TMPDIR"
@@ -148,14 +149,9 @@ install_rpm() {
     sudo rpm --install "$RPM_FILE"
 }
 
-check_path() {
-    info "Checking if it's available in the PATH..."
-    if ! has mangal; then
-        die "Looks like it's not :( Try installing it manually..."
-    fi
-}
-
 pre_install() {
+    has mangal && warn "mangal is installed already, reinstalling..."
+
     RELEASES_URL="https://github.com/metafates/mangal/releases"
     FILE_BASENAME="mangal"
 
@@ -166,21 +162,20 @@ pre_install() {
         rev)"
 
     test -z "$TAG" && {
-        echo "Unable to get mangal version." >&2
-        exit 1
+        die "Unable to get mangal version."
     }
-
-    test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
 
     OS=$(uname -s)
     ARCH=$(uname -m)
     VERSION=${TAG#?}
 
-    export RELEASES_URL FILE_BASENAME VERSION TAG OS ARCH
+    info "Latest version is $VERSION"
+
+    TMPDIR="$(mktemp -d)"
 }
 
 post_install() {
-    info "Mangal is now installed. You can run this script again to update it"
+    printf "\n🎉 \033[1;32mMangal was installed successfully\033[0m\n"
 }
 
 install() {
@@ -191,10 +186,14 @@ install() {
         info "macOS detected"
         install_macos
         ;;
-    *)
+    Linux)
         case $(cat /etc/*release | tr "[:upper:]" "[:lower:]") in
-        *ubuntu* | *debian*)
+        *debian*)
             info "Debian detected"
+            install_deb
+            ;;
+        *ubuntu*)
+            info "Ubuntu detected"
             install_deb
             ;;
         *fedora*)
@@ -207,9 +206,10 @@ install() {
             ;;
         esac
         ;;
+    *)
+        die "Unknown OS: $OS"
     esac
 
-    check_path
     post_install
 }
 
